apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: pv-mq
spec: 
  capacity: 
    storage: 3Gi 
  accessModes: 
   - ReadWriteMany 
  nfs: 
    server: 13.126.99.136
    path: /stwordpress
