apiVersion: v1 
kind: Service 
metadata: 
  name: myd-wp 
  labels: 
    app: wordpress
spec: 
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30045
  selector: 
    app: web 
  type: NodePort